# build with 'docker compose -f docker-compose.yml up --build'

version: '3'
services:
  api:
    container_name: manageapp-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - db
    networks:
      - manageapp-network
  db:
    container_name: manageapp-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_sw_process_management
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - manageapp-network
networks:
  manageapp-network:
    driver: bridge
volumes:
  pgdata: 
